// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GameSelectorController from "./game_selector_controller"
application.register("game-selector", GameSelectorController)

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)
